config/routes.rb
Rails.application.routes.draw do
  resources :messages
  root 'messages#index'
end

app/models/message.rb
class Message < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :find_message, only: [:show, :edit, :update, :destroy]

  def index
    @messages = Message.all.order("created_at DESC")
  end

  def show
    @message = Message.find(params[:id])
  end  

  def new
    @message = Message.new
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path
    else
      render 'new'
    end
  end

  def  edit


  end

  def update
  end

  def destroy
  end

  private

    def message_params
      params.require(:message).permit(:title, :description)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MessageBoard</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title, label: "Message Title" %>
  <%= f.input :title %>
  <%= f.button :submit %>
<% end %>

app/views/messages/index.html.erb
<h1>Welcome to my MessageBoard App</h1>

<% @messages.each do | message| %>
  <h2><%=message.title %></h2>
<% end %>

<%= link_to "New Message", new_message_path%>

app/views/messages/new.html.erb
<h1> New Message</h1>
<%= render 'form' %>

app/views/messages/show.html.erb
<h2><%= @message.title %></h2>
<p><%= @message.description %></p>
<!-- Add a posted at timestamp -->

<%= link_to "Edit", edit_message_path(@message) %>